//
//  git.swift
//  Guaka
//
//  Created by Omar Abdelhafith on 05/11/2016.
//
//

import Guaka

var root: Command!

// Autogenerated but you can edit

func createRoot() {
  
  root = try! Command(
    name: "git",
    flags: [
      Flag(longName: "debug", type: Bool.self, required: true),
      Flag(longName: "verbose", value: false, shortName: "v", inheritable: true),
      ]) { flags, args in
        print("Running git with \(flags) and \(args)")
  }
  
}
