//
//  rebase.swift
//  Guaka
//
//  Created by Omar Abdelhafith on 05/11/2016.
//
//

import Guaka

var rebase: Command!

// Autogenerated but you can edit

func createRebase() {
  
  rebase = Command(
  name: "rebase") { flags, args in
    
    // handle the command
    print("Running git with \(flags) and \(args)")
  }
  
  rebase.deprecationStatus = .deprecated("Dont use this")

  root.add(subCommands: rebase)
  
  
  // user will add these
  
  [
    Flag(longName: "foo", value: "", inheritable: true),
    Flag(longName: "remote", value: true, inheritable: true),
    Flag(longName: "bar", value: "", inheritable: false),
    Flag(longName: "xx", value: true, inheritable: false),
    ].forEach { rebase.add(flag: $0) }
  
  rebase.flags[0].deprecatedStatus = .deprecated("dont use thissss")
}

