//
//  setup.swift
//  Guaka
//
//  Created by Omar Abdelhafith on 05/11/2016.
//
//

import Guaka

// Autogenerated.. Don't edit
func setup() {
  
  createRoot()
  createRebase()
  createRemote()
  createShow()
  
}
